muza/Controllers/YoutubeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;
using muza.Attributes;
using muza.Helpers;
using muza.Models;
using YoutubeExtractor;
using Newtonsoft.Json.Linq;
using System.Web.Script.Serialization;
using Ionic.Zip;

namespace muza.Controllers
{

    public class YoutubeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        // [MultipleButton(Name = "action", Argument = "Chuj")]
        public ActionResult Chuj(YoutubeModel model)
        {
            return View();
        }

        [HttpPost]
        public ActionResult PlayEmbedded(List<string> urls)
        {
            var model = YoutubeHelper.GetEmbeddedYoutubeResults(urls);         
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult PlayAudio(YoutubeModel model)
        {
            return View(model);
        }

        [HttpGet]
        public ActionResult GetRawAudio(string url)
        {
            if (string.IsNullOrWhiteSpace(url))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var audioDownloader = new AudioDownloaderEntryClass(url);
            var title = string.Empty;
            var bytes = audioDownloader.GetMusicAsBytes(out title);
            var stream = new MemoryStream(bytes);
            return File(stream, "audio/wav");
        }

        [HttpPost]
        public ActionResult GetRawAudios(string urls)
        {
            if (string.IsNullOrWhiteSpace(urls))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var urlsparsed = new JavaScriptSerializer().Deserialize<List<string>>(urls);
            ZipFile zipFile = new ZipFile();

            foreach (var url in urlsparsed)
            {
                if (string.IsNullOrWhiteSpace(url))
                {
                    continue;
                }
                var trueUrl = url;
                if (trueUrl.Contains(@"&"))
                {
                    var split = url.Split('&')[0];
                    trueUrl = split;
                }

                var audioDownloader = new AudioDownloaderEntryClass(trueUrl);

                var title = string.Empty;
                byte[] fileBytes = null;
                string error = "";

                try
                {
                     fileBytes = audioDownloader.GetMusicAsBytes(out title);
                }
                catch (Exception e)
                {
                    error = $"nie dało się sciągnąć {url.Replace('/', ' ')}, sciagnij go recznie";
                   // throw new HttpException(, e);
                }

                if (fileBytes == null && !string.IsNullOrWhiteSpace(error))
                {
                    zipFile.AddEntry(error, new byte[] { });
                }
                else
                {
                    var fileName = title.Replace('/', ' ') + ".wav";
                    zipFile.AddEntry(fileName, fileBytes);
                }      
            }

            var stream = new MemoryStream();
            zipFile.Save(stream);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/zip", "jutub.zip");
        }

        public ActionResult Menu()
        {
            return PartialView();
        }
    }
}

muza/Views/Youtube/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row">
        <div class="input-group col-lg-6 col-md-6 col-sm-7 col-xs-8 help-block">
            <form id="savePlaylistForm" method="post" action="">
                <input id="playListNameInput" name="playListName" type="text" class="form-control" />
                <span class="input-group-btn">
                    <button class="btn" type="button" id="sendPlaylistButton">Zapisz</button>
                </span>
                <div class="alert alert-warning">Zapisuje obecnie istniejące youtubowe playery do playlisty</div>
            </form>
        </div>
    </div>
    <div class="row">
        <div>            
            <div>
                @Html.Partial("Menu")
            </div>
            <div class="col-lg-offset-8 col-md-offset-8 col-sm-offset-8 help-block">
                <div class="alert alert-warning">Przed "graj" kliknij w embedded video </div>
                <button id="playButton" class="btn btn-info" type="button">Graj <span class="glyphicon glyphicon-play"></span></button>
                <button id="nextButton" class="btn btn-info" type="button">Następne <span class="glyphicon glyphicon-forward"></span></button>
            </div>

            <div id="youtubeContainer">
                @*<div class="col-lg-6 col-md-6 col-sm-5 col-xs-4">
                        tu i tak nie jest nic wrzucany tylko do div w ktorym to jest zagniezdzone
                    </div>*@
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript" src="http://www.youtube.com/player_api"></script>
    <script type="text/javascript" src="https://www.youtube.com/iframe_api"></script>
    @Scripts.Render("~/bundles/myScripts")
}

muza/Views/Youtube/Menu.cshtml
<div class="input-group col-lg-6 col-md-6 col-sm-7 col-xs-8">
    <form id="audioVideoForm" method="post" action="">
        
        <label class="control-label">Daj linka</label>
        <div id="buttonDivContainer">
            <input type="text" name="url0" class="form-control">
            <span class="input-group-btn">
                <button id="addNewInputButton" class="btn btn-default" type="button">dodaj kolejny link!</button>
            </span>
        </div>
        @*<div class="input-group">
            <span class="input-group-btn">
                <button id="clearData" class="btn btn-warning" type="button">wyczyść filmiki poniżej</button>
            </span>
        </div>*@
        <div class="help-block">
            <div class="btn-toolbar">
                <div class="btn-group">
                    <button type="button" class="btn btn-primary" id="Embedded">Embedded video</button>
                    <button type="button" class="btn btn-primary" id="audio">Download audio</button>
                </div>               
            </div>
            <div class="alert alert-warning">Do ściągnięcia się nadają filmiki do około 10 minut </div>
        </div>
    </form>
</div>

muza/Views/Youtube/PlayAudio.cshtml
@model muza.Models.YoutubeModel

<audio controls>
    @*<source src="@Url.Action("PlayRawAudio","Youtube", new {url = Model.url})" type="audio/wav" />*@
    <source src="/Youtube/PlayRawAudio?url=@Model.url" type="audio/wav" />
</audio>

muza/Views/Youtube/PlayEmbedded.cshtml
@using muza.Helpers
@model IEnumerable<muza.Models.YoutubeModel>


@foreach (var item in Model)
{
    if (!string.IsNullOrWhiteSpace(item.result))
    {
        <div class="jumbotron" id="player@(Model.IndexOf(item))Container">
            <h3>@item.title </h3>
            <p>@item.url</p>
            <p>@Html.Raw(item.result)</p>
        </div>
    }
}
@*<div class="jumbotron" id="player@(Model.IndexOf(item))">
    <h3>@item.title </h3>
    <p>@item.url</p>
    <p>@Html.Raw(item.result)</p>
</div>*@